ticket:
  # redmine, github or gitconfig
  source: github

redmine:
  url: https://codefirst.org/redmine/
  project: dashbozu
  # or 'git config redmine.apikey your_key'

github:
  group: codefirst
  project: dashbozu
